<!-- resources/views/teamlead/reports/comprehensive-pdf.blade.php -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Comprehensive Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
            line-height: 1.6;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 28px;
            margin-bottom: 10px;
        }
        .header p {
            font-size: 14px;
            opacity: 0.9;
        }
        .meta-info {
            background: #f8f9fa;
            padding: 15px;
            margin-bottom: 20px;
            border-left: 4px solid #667eea;
        }
        .meta-info table {
            width: 100%;
        }
        .meta-info td {
            padding: 5px 0;
        }
        .meta-info strong {
            color: #667eea;
        }
        h2 {
            color: #667eea;
            font-size: 18px;
            margin: 25px 0 15px 0;
            padding-bottom: 5px;
            border-bottom: 2px solid #667eea;
        }
        h3 {
            color: #764ba2;
            font-size: 16px;
            margin: 20px 0 10px 0;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-box {
            display: table-cell;
            width: 25%;
            padding: 15px;
            text-align: center;
            background: #f8f9fa;
            border: 1px solid #e9ecef;
        }
        .stat-box .number {
            font-size: 32px;
            font-weight: bold;
            color: #667eea;
            display: block;
            margin-bottom: 5px;
        }
        .stat-box .label {
            font-size: 11px;
            color: #6c757d;
            text-transform: uppercase;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        th {
            background: #667eea;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 11px;
            font-weight: bold;
        }
        td {
            padding: 8px 10px;
            border-bottom: 1px solid #e9ecef;
        }
        tr:hover {
            background: #f8f9fa;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-todo { background: #cfe2ff; color: #084298; }
        .badge-progress { background: #fff3cd; color: #997404; }
        .badge-review { background: #e0cffc; color: #6f42c1; }
        .badge-done { background: #d1e7dd; color: #0f5132; }
        .badge-high { background: #f8d7da; color: #842029; }
        .progress-bar {
            width: 100%;
            height: 20px;
            background: #e9ecef;
            border-radius: 4px;
            overflow: hidden;
        }
        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
            text-align: center;
            color: white;
            font-size: 10px;
            line-height: 20px;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 2px solid #e9ecef;
            text-align: center;
            font-size: 10px;
            color: #6c757d;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>📊 COMPREHENSIVE PROJECT REPORT</h1>
        <p>Complete Overview of All Projects and Team Performance</p>
    </div>

    <!-- Meta Info -->
    <div class="meta-info">
        <table>
            <tr>
                <td width="50%"><strong>Generated By:</strong> {{ $generatedBy->full_name }}</td>
                <td><strong>Generated At:</strong> {{ $generatedAt->format('d M Y, H:i') }}</td>
            </tr>
            @if($startDate && $endDate)
            <tr>
                <td colspan="2">
                    <strong>Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}
                </td>
            </tr>
            @else
            <tr>
                <td colspan="2"><strong>Period:</strong> All Time</td>
            </tr>
            @endif
        </table>
    </div>

    <!-- Overall Statistics -->
    <h2>📈 Overall Statistics</h2>
    <div class="stats-grid">
        <div class="stat-box">
            <span class="number">{{ $overallStats['total_projects'] }}</span>
            <span class="label">Active Projects</span>
        </div>
        <div class="stat-box">
            <span class="number">{{ $overallStats['total_tasks'] }}</span>
            <span class="label">Total Tasks</span>
        </div>
        <div class="stat-box">
            <span class="number">{{ $overallStats['completed_tasks'] }}</span>
            <span class="label">Completed</span>
        </div>
        <div class="stat-box">
            <span class="number">{{ $overallStats['total_team_members'] }}</span>
            <span class="label">Team Members</span>
        </div>
    </div>

    <!-- Projects Overview -->
    <h2>📁 Projects Overview</h2>
    @foreach($projects as $project)
    <h3>{{ $loop->iteration }}. {{ $project->project_name }}</h3>
    
    <table style="margin-bottom: 10px;">
        <tr>
            <td width="30%"><strong>Creator:</strong></td>
            <td>{{ $project->creator->full_name }}</td>
        </tr>
        <tr>
            <td><strong>Deadline:</strong></td>
            <td>{{ $project->deadline ? $project->deadline->format('d M Y') : 'No deadline' }}</td>
        </tr>
        <tr>
            <td><strong>Team Members:</strong></td>
            <td>{{ $project->members->count() }} members</td>
        </tr>
        <tr>
            <td><strong>Progress:</strong></td>
            <td>
                <div class="progress-bar">
                    <div class="progress-fill" style="width: {{ $project->progress }}%">
                        {{ $project->progress }}%
                    </div>
                </div>
            </td>
        </tr>
    </table>

    @php
        $projectCards = $project->boards->flatMap->cards;
        $todoCount = $projectCards->where('status', 'todo')->count();
        $progressCount = $projectCards->where('status', 'in_progress')->count();
        $reviewCount = $projectCards->where('status', 'review')->count();
        $doneCount = $projectCards->where('status', 'done')->count();
    @endphp

    <table>
        <thead>
            <tr>
                <th>Task Status</th>
                <th width="15%">Count</th>
                <th width="15%">Percentage</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>To Do</td>
                <td style="text-align: center;">{{ $todoCount }}</td>
                <td style="text-align: center;">{{ $projectCards->count() > 0 ? round(($todoCount / $projectCards->count()) * 100) : 0 }}%</td>
            </tr>
            <tr>
                <td>In Progress</td>
                <td style="text-align: center;">{{ $progressCount }}</td>
                <td style="text-align: center;">{{ $projectCards->count() > 0 ? round(($progressCount / $projectCards->count()) * 100) : 0 }}%</td>
            </tr>
            <tr>
                <td>Review</td>
                <td style="text-align: center;">{{ $reviewCount }}</td>
                <td style="text-align: center;">{{ $projectCards->count() > 0 ? round(($reviewCount / $projectCards->count()) * 100) : 0 }}%</td>
            </tr>
            <tr>
                <td><strong>Done</strong></td>
                <td style="text-align: center;"><strong>{{ $doneCount }}</strong></td>
                <td style="text-align: center;"><strong>{{ $projectCards->count() > 0 ? round(($doneCount / $projectCards->count()) * 100) : 0 }}%</strong></td>
            </tr>
        </tbody>
    </table>

    <!-- High Priority Tasks for this project -->
    @php
        $highPriorityTasks = $projectCards->where('priority', 'high')->whereIn('status', ['todo', 'in_progress', 'review'])->take(5);
    @endphp

    @if($highPriorityTasks->count() > 0)
    <p style="margin-top: 15px;"><strong>⚠️ High Priority Tasks:</strong></p>
    <table>
        <thead>
            <tr>
                <th>Task</th>
                <th width="25%">Assigned To</th>
                <th width="20%">Due Date</th>
                <th width="15%">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($highPriorityTasks as $task)
            <tr>
                <td>{{ $task->card_title }}</td>
                <td>
                    @if($task->assignedMembers->count() > 0)
                        {{ $task->assignedMembers->pluck('full_name')->join(', ') }}
                    @else
                        <em>Unassigned</em>
                    @endif
                </td>
                <td>{{ $task->due_date ? $task->due_date->format('d M Y') : '-' }}</td>
                <td>
                    <span class="badge badge-{{ $task->status }}">
                        {{ ucfirst(str_replace('_', ' ', $task->status)) }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if(!$loop->last)
    <div style="margin: 30px 0; border-bottom: 2px dashed #dee2e6;"></div>
    @endif
    @endforeach

    <div class="page-break"></div>

    <!-- Team Performance -->
    <h2>👥 Team Performance</h2>
    <table>
        <thead>
            <tr>
                <th>Team Member</th>
                <th width="12%">Total Tasks</th>
                <th width="12%">Completed</th>
                <th width="12%">In Progress</th>
                <th width="15%">Completion Rate</th>
                <th width="12%">Total Hours</th>
                <th width="15%">Avg Hours/Task</th>
            </tr>
        </thead>
        <tbody>
            @foreach($teamPerformance as $performance)
            <tr>
                <td>
                    <strong>{{ $performance['member']->full_name }}</strong><br>
                    <small style="color: #6c757d;">{{ ucfirst($performance['member']->role) }}</small>
                </td>
                <td style="text-align: center;">{{ $performance['total_tasks'] }}</td>
                <td style="text-align: center;">{{ $performance['completed_tasks'] }}</td>
                <td style="text-align: center;">{{ $performance['in_progress_tasks'] }}</td>
                <td>
                    <div class="progress-bar" style="height: 15px;">
                        <div class="progress-fill" style="width: {{ $performance['completion_rate'] }}%; font-size: 9px; line-height: 15px;">
                            {{ $performance['completion_rate'] }}%
                        </div>
                    </div>
                </td>
                <td style="text-align: center;">{{ number_format($performance['total_hours'], 1) }}h</td>
                <td style="text-align: center;">{{ number_format($performance['avg_hours_per_task'], 1) }}h</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>This report was automatically generated by the Project Management System</p>
        <p>© {{ date('Y') }} - Confidential Document</p>
    </div>
</body>
</html>