<!-- resources/views/teamlead/reports/project-pdf.blade.php -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Project Report - {{ $project->project_name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; font-size: 11px; color: #333; line-height: 1.5; }
        .header {
            background: linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%);
            color: white;
            padding: 25px;
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 { font-size: 24px; margin-bottom: 8px; }
        .header p { font-size: 13px; opacity: 0.9; }
        .section { margin: 20px 0; }
        h2 {
            color: #3b82f6;
            font-size: 16px;
            margin: 20px 0 12px 0;
            padding-bottom: 5px;
            border-bottom: 2px solid #3b82f6;
        }
        h3 { color: #8b5cf6; font-size: 14px; margin: 15px 0 8px 0; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th {
            background: #3b82f6;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 10px;
            font-weight: bold;
        }
        td { padding: 7px 8px; border-bottom: 1px solid #e5e7eb; }
        tr:hover { background: #f9fafb; }
        .badge {
            display: inline-block;
            padding: 3px 7px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
        }
        .badge-high { background: #fecaca; color: #991b1b; }
        .badge-medium { background: #fef3c7; color: #92400e; }
        .badge-low { background: #d1fae5; color: #065f46; }
        .progress-bar {
            width: 100%;
            height: 18px;
            background: #e5e7eb;
            border-radius: 3px;
            overflow: hidden;
        }
        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #3b82f6 0%, #8b5cf6 100%);
            text-align: center;
            color: white;
            font-size: 9px;
            line-height: 18px;
            font-weight: bold;
        }
        .stats-grid { display: table; width: 100%; margin: 15px 0; }
        .stat-box {
            display: table-cell;
            width: 20%;
            padding: 12px;
            text-align: center;
            background: #f9fafb;
            border: 1px solid #e5e7eb;
        }
        .stat-box .number {
            font-size: 24px;
            font-weight: bold;
            color: #3b82f6;
            display: block;
        }
        .stat-box .label {
            font-size: 9px;
            color: #6b7280;
            text-transform: uppercase;
        }
        .footer {
            margin-top: 25px;
            padding-top: 12px;
            border-top: 2px solid #e5e7eb;
            text-align: center;
            font-size: 9px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📁 {{ $project->project_name }}</h1>
        <p>Project Report - {{ $generatedAt->format('d F Y') }}</p>
    </div>

    <!-- Meta Info -->
    <table style="margin-bottom: 20px; border: 1px solid #e5e7eb;">
        <tr>
            <td width="25%"><strong>Project Creator:</strong></td>
            <td>{{ $project->creator->full_name }}</td>
            <td width="25%"><strong>Report Generated By:</strong></td>
            <td>{{ $generatedBy->full_name }}</td>
        </tr>
        <tr>
            <td><strong>Created Date:</strong></td>
            {{--  <td>{{ $project->created_at ? $project->created_at->format('d M Y') : '' }}</td>  --}}
            <td><strong>Deadline:</strong></td>
            <td>{{ $project->deadline ? $project->deadline->format('d M Y') : 'No deadline' }}</td>
        </tr>
        @if($startDate && $endDate)
        <tr>
            <td><strong>Report Period:</strong></td>
            <td colspan="3">
                {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} - 
                {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}
            </td>
        </tr>
        @endif
    </table>

    <!-- Project Description -->
    <h2>📝 Description</h2>
    <p style="padding: 10px; background: #f9fafb; border-left: 3px solid #3b82f6;">
        {{ $project->description ?: 'No description provided.' }}
    </p>

    <!-- Statistics -->
    <h2>📊 Project Statistics</h2>
    <div class="stats-grid">
        <div class="stat-box">
            <span class="number">{{ $stats['total_tasks'] }}</span>
            <span class="label">Total Tasks</span>
        </div>
        <div class="stat-box">
            <span class="number">{{ $stats['completed_tasks'] }}</span>
            <span class="label">Completed</span>
        </div>
        <div class="stat-box">
            <span class="number">{{ $stats['in_progress_tasks'] }}</span>
            <span class="label">In Progress</span>
        </div>
        <div class="stat-box">
            <span class="number">{{ $stats['progress'] }}%</span>
            <span class="label">Progress</span>
        </div>
        <div class="stat-box">
            <span class="number">{{ number_format($stats['total_actual_hours'], 1) }}h</span>
            <span class="label">Hours Logged</span>
        </div>
    </div>

    <!-- Progress Bar -->
    <div style="margin: 15px 0;">
        <p style="margin-bottom: 5px;"><strong>Overall Progress:</strong></p>
        <div class="progress-bar">
            <div class="progress-fill" style="width: {{ $stats['progress'] }}%">
                {{ $stats['progress'] }}% Complete
            </div>
        </div>
    </div>

    <!-- Task Breakdown -->
    <h2>📋 Task Status Breakdown</h2>
    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th width="15%">Count</th>
                <th width="15%">Percentage</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>To Do</td>
                <td style="text-align: center;">{{ $stats['todo_tasks'] }}</td>
                <td style="text-align: center;">
                    {{ $stats['total_tasks'] > 0 ? round(($stats['todo_tasks'] / $stats['total_tasks']) * 100) : 0 }}%
                </td>
            </tr>
            <tr>
                <td>In Progress</td>
                <td style="text-align: center;">{{ $stats['in_progress_tasks'] }}</td>
                <td style="text-align: center;">
                    {{ $stats['total_tasks'] > 0 ? round(($stats['in_progress_tasks'] / $stats['total_tasks']) * 100) : 0 }}%
                </td>
            </tr>
            <tr>
                <td>Review</td>
                <td style="text-align: center;">{{ $stats['review_tasks'] }}</td>
                <td style="text-align: center;">
                    {{ $stats['total_tasks'] > 0 ? round(($stats['review_tasks'] / $stats['total_tasks']) * 100) : 0 }}%
                </td>
            </tr>
            <tr style="background: #f0fdf4;">
                <td><strong>Done</strong></td>
                <td style="text-align: center;"><strong>{{ $stats['completed_tasks'] }}</strong></td>
                <td style="text-align: center;">
                    <strong>{{ $stats['total_tasks'] > 0 ? round(($stats['completed_tasks'] / $stats['total_tasks']) * 100) : 0 }}%</strong>
                </td>
            </tr>
        </tbody>
    </table>

    <!-- High Priority Tasks -->
    @php
        $highPriorityTasks = $project->boards->flatMap->cards
            ->where('priority', 'high')
            ->whereIn('status', ['todo', 'in_progress', 'review']);
    @endphp

    @if($highPriorityTasks->count() > 0)
    <h2>⚠️ High Priority Tasks</h2>
    <table>
        <thead>
            <tr>
                <th>Task Name</th>
                <th width="25%">Assigned To</th>
                <th width="18%">Due Date</th>
                <th width="12%">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($highPriorityTasks as $task)
            <tr>
                <td>{{ $task->card_title }}</td>
                <td>
                    @if($task->assignedMembers->count() > 0)
                        {{ $task->assignedMembers->pluck('full_name')->join(', ') }}
                    @else
                        <em style="color: #9ca3af;">Unassigned</em>
                    @endif
                </td>
                <td>
                    @if($task->due_date)
                        {{ $task->due_date->format('d M Y') }}
                        @if($task->is_overdue)
                            <span class="badge" style="background: #fee2e2; color: #991b1b;">OVERDUE</span>
                        @endif
                    @else
                        -
                    @endif
                </td>
                <td style="text-align: center;">
                    {{ ucfirst(str_replace('_', ' ', $task->status)) }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <!-- Team Members -->
    <h2>👥 Team Members ({{ $project->members->count() }})</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Role</th>
                <th width="15%">Tasks Assigned</th>
                <th width="15%">Tasks Completed</th>
                <th width="15%">Completion Rate</th>
            </tr>
        </thead>
        <tbody>
            @foreach($project->members as $member)
    
            <tr>
                <td>{{ $member->full_name }}</td>
                <td>{{ ucfirst($member->role) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Time Tracking -->
    @if($stats['total_estimated_hours'] > 0)
    <h2>⏱️ Time Tracking</h2>
    <table>
        <tr>
            <td width="40%"><strong>Total Estimated Hours:</strong></td>
            <td>{{ number_format($stats['total_estimated_hours'], 1) }} hours</td>
        </tr>
        <tr>
            <td><strong>Total Actual Hours:</strong></td>
            <td>{{ number_format($stats['total_actual_hours'], 1) }} hours</td>
        </tr>
        <tr>
            <td><strong>Difference:</strong></td>
            <td>
                @php
                    $diff = $stats['total_actual_hours'] - $stats['total_estimated_hours'];
                    $diffColor = $diff > 0 ? '#dc2626' : '#16a34a';
                @endphp
                <span style="color: {{ $diffColor }}; font-weight: bold;">
                    {{ $diff > 0 ? '+' : '' }}{{ number_format($diff, 1) }} hours
                    ({{ $diff > 0 ? 'Over' : 'Under' }} estimate)
                </span>
            </td>
        </tr>
    </table>
    @endif

    <div class="footer">
        <p>Generated by {{ $generatedBy->full_name }} on {{ $generatedAt->format('d F Y, H:i') }}</p>
        <p>© {{ date('Y') }} Project Management System - Confidential</p>
    </div>
</body>
</html>